platform :ios, '5.1'
pod 'JSONKit', '~>1.5pre'
pod 'SVProgressHUD', '~> 0.9'
pod 'TouchXML', '~> 0.1'
pod 'US2FormValidator', '~> 1.0.9'
pod 'TTTAttributedLabel', '~> 1.4.1'
pod 'OHAttributedLabel', '~> 3.3.0'
pod 'ODRefreshControl', '~> 1.1.0'
pod 'FormatterKit', '~> 1.1.2'
pod 'CocoaLumberjack', '~> 1.6.2'
pod 'PSTCollectionView', '~> 0.0.1'
pod 'SFHFKeychainUtils', '~> 0.0.1'
pod 'DCRoundSwitch', '~> 0.0.1'
pod 'SVWebViewController', '~> 0.1'
pod 'RSOAuthEngine', '~> 1.0.0'
pod 'ReactiveCocoa', '~> 0.13.1'
pod 'Mantle', '~> 0.2.3'
pod 'iRate', '~> 1.7.5'
pod 'DYRateView', '~>0.0.2'

xcodeproj 'OOTD.xcodeproj'
